include "application.conf"

sim {
  graphFile = "src/main/resources/graphs/SmallGraph.ngs"
  seed = 42
  runDurationSeconds = 30

  traffic {
    tickIntervalMs = 100
    defaultPdf = [
      { msg = "PING", p = 0.70 },
      { msg = "WORK", p = 0.30 }
    ]
    perNodePdf = []
  }
}